version: '3.1'
services:
  ant-live:
    build:
      context: .
      dockerfile: Dockerfile
    image: ant-live:latest
    container_name: ant-live
    ports:
      - '8080:8080'
    environment:
      - 'SPRING_REDIS_HOST=127.0.0.1'
      - 'SPRING_REDIS_PORT=6379'
      - 'SPRING_REDIS_PASSWORD=123456'
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://127.0.0.1:3306/ant-live?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false'
      - 'SPRING_DATASOURCE_USERNAME=root'
      - 'SPRING_DATASOURCE_PASSWORD=123456'
    depends_on:
      - redis
      - mysql
      - minio
    external_links:
      - redis:redis
      - mysql:mysql
      - minio:minio
  redis:
    image: redis:latest
    container_name: ant-live-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - '/opt/dev/docker/redis/data:/data'
      - '/opt/dev/docker/redis/redis.conf:/etc/redis/redis.conf'
    command: redis-server --appendonly yes --requirepass 123456
  mysql:
    image: mysql/mysql-server:latest
    container_name: ant-live-mysql
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - '/home/mysql:/var/lib/mysql'
      - '/home/mysql/init:/docker-entrypoint-initdb.d/'
  nginx:
    image: nginx:latest
    container_name: ant-live-nginx
    privileged: true
    restart: always
    ports:
      - '80:80'
    volumes:
      - '/home/nginx/conf/nginx.conf:/etc/nginx/nginx.conf'
      - '/home/nginx/html/:/usr/share/nginx/html'
  minio:
    image: minio/minio:latest
    hostname: "minio"
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio_pass
    volumes:
      - '/home/minio/data:/data'
      - '/home/minio/config:/root/.minio/'
    command: server --console-address ":9001" /data
