server:
  port: 9000

spring:
  # 数据库配置必填
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ant-live?characterEncoding=utf-8&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-wait: 60000
      initial-size: 5
      min-idle: 5
      max-active: 20
  # redis配置必填
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 8
    timeout: 5000
  servlet:
    multipart:
      enabled: true
      max-file-size: 4096MB
      max-request-size: 4096MB
  mail:
    host: smtp.qq.com
    username: xxx@qq.com
    password: xxx
    default-encoding: UTF-8
    port: 465
    protocol: smtps
tencent:
  # 腾讯云sms短信服务，非必填
  sms:
    appid: 000
    appkey: 000
    templateId: 000
    templateNoticeId: 000
    smsSign: 000
  # 腾讯云直播服务，非必填
  live:
    liveDomain: live.imhtb.cn
    playDomain: play.imhtb.cn
    appName: live
    secretId: 000
    secretKey: 000
  # 腾讯云对象存储服务，非必填
  cos:
    bucketName: 000
    path: https://xxx.cos.ap-chengdu.myqcloud.com/

#logging:
mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: auto
      logic-not-delete-value: 0
      logic-delete-value: 1
#  config: classpath:logback.xml

alipay:
  path: Q:/Learning/Live/BackEnd/AntLive/src/main/resources/static/